spring:
  datasource:
    url: jdbc:mysql://10.10.15.218:3306/ip_checklist?useSSL=false&allowPublicKeyRetrieval=true&wait_timeout=28800
    username: dbdevl3
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

 #LDAP configuration
ldap:
  url: ldap://vdc-ldap1.esic.gov.in:1389
  base: ou=employeegroup,o=esic.in,o=esic
  userDn: cn=snsadmin,ou=admin,o=esic
  password: ${LDAP_PASSWORD}
  # Which attribute to search users by (cn / uid / sAMAccountName)
  userSearchAttribute: cn
  
jwt:
  secret: ${JWT_SECRET}
  expiration: 1800000 #(30 minutes)

bhashini:
  api:
    endpoint: https://anuvaad-backend.bhashini.co.in/v1/pipeline
    ulcaApiKey: ${ULCA_API_KEY}
    userId: c6f96da78b7b464b99766144690bbab3
  translation:
    serviceId: ai4bharat/indictrans-v2-all-gpu--t4
  tts:
    serviceId: ai4bharat/indic-tts-coqui-indo_aryan-gpu--t4
  
cors:
  allowed-origins: http://localhost:5173
  
url:
  his:
    endpoint: http://10.10.36.21/INS_HIS_LiveLIst/HIS/LiveListDetails


# logging location and levels
logging:
  level:
    root: INFO
  file:
    path: /opt/appsrv/narisakthiapp/logs/
