spring:
  datasource:
    url: jdbc:mysql://10.10.13.54:3307/ip_checklist?useSSL=false&allowPublicKeyRetrieval=true&wait_timeout=28800
    username: dbdevl3
    password: lxEC03haDMdb
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 9090

bhasini:
  base-url: "https://api.bhashini.gov.in"
  api-key: "DEV_API_KEY"
  secret: "DEV_SECRET"
  
cors:
  allowed-origins: http://localhost:5173
  
  # Google Cloud project
google:
 project-id: project-4d5709f9-bba1-4874-984
 translate.location: global
 api-key: AIzaSyAeoedB74zQZiKRDBnIopfrz95hu4B1VIU


