spring:
  datasource:
    #url: jdbc:mysql://10.10.13.54:3307/ip_checklist?useSSL=false&allowPublicKeyRetrieval=true&wait_timeout=28800
    #username: dbdevl3
    #password: lxEC03haDMdb
    url: jdbc:mysql://localhost:3306/ip_checklist?useSSL=false&allowPublicKeyRetrieval=true&wait_timeout=28800
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

 #LDAP configuration
ldap:
  url: ldap://esic-oud-01.esic.gov.in:1389
  base: ou=employeegroup,o=esic.in,o=esic
  userDn: cn=socadmin,ou=admin,o=esic
  password: SOC@2025#admin
  # Which attribute to search users by (cn / uid / sAMAccountName)
  userSearchAttribute: cn
  
  
jwt:
  secret: 47528693cc1b4c1d62888eddfe97633bf7d91a78de844fa2c44c34a0ad30aa72
  expiration: 180000 #(30 minutes)


server:
  port: 9090

bhashini:
  api:
    endpoint: https://anuvaad-backend.bhashini.co.in/v1/pipeline
    ulcaApiKey: 0928306623-67cd-4e15-be92-4b0ca33a6204
    userId: c6f96da78b7b464b99766144690bbab3
  translation:
    serviceId: ai4bharat/indictrans-v2-all-gpu--t4
  tts:
    serviceId: ai4bharat/indic-tts-coqui-indo_aryan-gpu--t4
  
cors:
  allowed-origins: http://localhost:5173
  
url:
  his:
    endpoint: http://10.10.13.131/INS_HIS_LiveLIst/HIS/LiveListDetails


